### ISSUE TITLE
vite2+VUE3+vue-qr 启动报错

### ISSUE THREAD

**Issue by HbuJiaTian** [Binaryify/vue-qr#108]
问题描述：
Uncaught SyntaxError: The requested module '/node_modules/js-binary-schema-parser/lib/schemas/gif.js?v=533b583c' does not provide an export named 'default'

问题展示：
![image](https://user-images.githubusercontent.com/10797390/147571120-170097bd-97c9-4876-9b94-963543737792.png)

**Comment by polichan** [comment]
有解决办法吗？

**Comment by renleiabc** [comment]
怎么解决
