### ISSUE TITLE
在ios上二维码无效，不能被扫码

### ISSUE THREAD

**Issue by xu-Aurora** [Binaryify/vue-qr#109]
在android上生成的二维码是正常的，码也可以被扫。但ios上生成的二位是无效的，不能被扫，一扫就报“无效二维码”。
vue-qr库试了最新版本的和2.2.1的版本都不可以。ios手机xr和iphone12

**Comment by xu-Aurora** [comment]
生成的二维码，用我公司的机器是可以读取里面的内容的，android生成的二维码机器可以读取里面的数据，并显示出来。ios生成的二维码，用机器去扫，就报“无效二维码”的提示

**Comment by Binaryify** [comment]
参数多少
