### ISSUE TITLE
部分机型不兼容

### ISSUE THREAD

**Issue by huyongyong1992** [Binaryify/vue-qr#11]
iphone6(A1586) 系统 10.0.2 以及部分安卓机型（具体未反馈），无法生成带logo的二维码（开始以为logo太大，但logo缩小为20*20还是无法生成）。

**Comment by CCWork** [comment]
[https://github.com/Binaryify/vue-qr/issues/23](url)
这个原因导致的。

**Comment by CCWork** [comment]
#23 
大兄弟，是这个原因导致的。

**Comment by Binaryify** [comment]
试试 v1.2.9
