### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by zzzZZZ1117** [Binaryify/vue-qr#113]
**Warning: Missing input files:
C:\GTK\bin\libpangoft2-1.0-0.dll
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libintl-8.dll...**
安装成功后webpack打包时还是会报这个错误，并且会报一些node-gyp的错误，node版本：v14.17.1，node-gyp: v5.1.0

**Comment by Binaryify** [comment]
用cnpm 安装依赖试试

**Comment by Binaryify** [comment]
新版本已经移除canvas的依赖了，现在安装应该没啥阻碍了

**Comment by zzzZZZ1117** [comment]
回头试试

**Comment by zzzZZZ1117** [comment]
验证通过

**Comment by Binaryify** [comment]
嗯
