### ISSUE TITLE
does not provide an export named 'default'

### ISSUE THREAD

**Issue by renleiabc** [Binaryify/vue-qr#117]
SyntaxError: The requested module '/node_modules/js-binary-schema-parser/lib/schemas/gif.js?v=7782b26a' does not provide an export named 'default'
![image](https://user-images.githubusercontent.com/24283195/156709562-d9d76533-511a-41ff-9001-ea61a2ad44de.png)

**Comment by renleiabc** [comment]
不要使用yarn add vue-qr安装；
要使用 cnpm install  vue-qr -S

**Comment by youyou12344** [comment]
试试看，重新 npm run dev 一下，可能会有惊喜。

**Comment by EnriqueWitte** [comment]
I have the same error ......

**Comment by Binaryify** [comment]
新版本应该不会报这个错了

**Comment by cffycls** [comment]
2022.05.07最新版
Uncaught (in promise) SyntaxError: The requested module '/node_modules/_path-browserify@1.0.1@path-browserify/index.js?v=6114ed79' does not provide an export named 'basename'
