### ISSUE TITLE
[求助] path-browserify   does not provide an export named 'basename'

### ISSUE THREAD

**Issue by jimmyrogue** [Binaryify/vue-qr#122]
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/6006189/165488853-ff691492-d6a0-4ce1-8aa2-eb669e09993d.png">

'/node_modules/path-browserify/index.js?v=6851af60' does not provide an export named 'basename'

**Comment by jimmyrogue** [comment]
对了我用的是vite2

**Comment by jimmyrogue** [comment]
@Binaryify 就是
```
<vue-qr text="xxxxxx" :size="200"></vue-qr>

import vueQr from 'vue-qr/src/packages/vue-qr.vue';
```

setup语法

**Comment by jimmyrogue** [comment]
一个细节，我是在装了 [vue-cropper](https://github.com/xyxiao001/vue-cropper) 后开始报错的

**Comment by Binaryify** [comment]
无法复现
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/12221718/165492949-0262063c-4a3a-40d8-8881-9da3ee33a85c.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12221718/165492994-beef4eb2-6673-44c9-a6ff-f6bfa9fb4342.png">

**Comment by jimmyrogue** [comment]
@Binaryify 我的vite是2.8.x，升级了2.9.6就好了。
感谢
