### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by waysagency** [Binaryify/vue-qr#133]
Any plans on Nuxt 3 support? I'm now getting errors

```node
[nuxt] [request error] [unhandled] [500] window is not defined
  at $id_hUmYHrepnE (/C:/frontend/.nuxt/dist/server/server.mjs:7890:5)    
  at async __instantiateModule__ (/C:/frontend/.nuxt/dist/server/server.mjs:121789:3)
```

**Comment by Binaryify** [comment]
plz use `<client-only><vue-qr></vue-qr></client-only>`  instead

**Comment by waysagency** [comment]
```vue
<script setup>
import vueQr from "vue-qr/src/packages/vue-qr.vue";
</script>

<template>
  <div>
    <client-only><vue-qr></vue-qr></client-only>
  </div>
</template>

```

![image](https://user-images.githubusercontent.com/76130749/194406053-64a83781-56f5-46cc-bf15-ff4a339bdc1b.png)

**Comment by waysagency** [comment]
Alright I've got it working now. Had to add the package to build.transpile.

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ["vue-qr", "@diadal/vue3-qr-code-styling"],
  },
});
```

But now I have some issues with the appearence of the qr code.

Here is my code

```vue
<script setup lang="ts">
import vueQr from "vue-qr/src/packages/vue-qr.vue";

const ComponentOptions = reactive({
  data: {
    scale: 1,
  },
  timing: {
    scale: 1,
    protectors: true,
  },
  alignment: {
    scale: 0.5,
    protectors: true,
  },
  cornerAlignment: {
    scale: 0.5,
    protectors: true,
  },
});
</script>

<template>
  <div>
    <ClientOnly>
      <vueQr text="https://test.nl/" :size="500" :components="ComponentOptions"></vueQr>
    </ClientOnly>
  </div>
</template>
```

And this is what it looks like

![image](https://user-images.githubusercontent.com/76130749/194564342-31d76f05-a475-4b56-a877-1e31727dbab0.png)

**Comment by Binaryify** [comment]
>But now I have some issues with the appearence of the qr code.

what issues you mean

**Comment by waysagency** [comment]
Look at the bottom right square. There are the small squares smaller then the rest of the squares. Don't think this is normal behaviour

**Comment by Binaryify** [comment]
plz set cornerAlignment's scale to 1

**Comment by huyanyou** [comment]
我加了client-only还是出现window is not defined

**Comment by lcrislforcel** [comment]
It turns out that I have the same problem, I added the build in the nuxt configuration, however it gives me another error, about 'TextEncoder is not defined', I could see that the error occurs in the /io.js file

**Comment by Binaryify** [comment]
<img width="2494" alt="image" src="https://github.com/Binaryify/vue-qr/assets/12221718/263d6fa8-6b87-4478-8f30-389bfa685314">
make sure you use 
import vueQr from 'vue-qr/src/packages/vue-qr.vue'
and ClientOnly tag
