### ISSUE TITLE
npm vue-qr 报错

### ISSUE THREAD

**Issue by 35860368** [Binaryify/vue-qr#16]
D:\Program Files\git-projects\hops-aportal\node_modules\canvas>if not defined npm_config_node_gyp (node "D:\AppData\Roaming\nvm\v8.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(54,5): error MSB8020: The build tools for Visual St
udio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools
.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then
selecting "Retarget solution". [D:\Program Files\git-projects\hops-aportal\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\AppData\Roaming\nvm\v8.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\AppData\\Roaming\\nvm\\v8.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Program Files\git-projects\hops-aportal\node_modules\canvas
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xieke\AppData\Roaming\npm-cache\_logs\2017-12-25T03_39_54_805Z-debug.log

**Comment by oyster0118** [comment]
最后怎么解决的？

**Comment by 35860368** [comment]
换成其他的qr了，因为它这个组件需要用到windos的一些组件库，而且这个他用的是1.08的awesome-qr，而这个版本awesome-qr会有url过长会报长度超出的错误。

**Comment by Binaryify** [comment]
这几天会升级下

**Comment by Binaryify** [comment]
建议先用着 1.2的版本, npm i vue-qr@1.2.0 --save

**Comment by Binaryify** [comment]
已更新

**Comment by cbrghton** [comment]
Same problem

**Comment by Binaryify** [comment]
@cbrghton 确定?新版本不需要编译的
