### ISSUE TITLE
npm install 报错 装不上

### ISSUE THREAD

**Issue by caoshining** [Binaryify/vue-qr#17]
![image](https://user-images.githubusercontent.com/19256823/34549706-bb6c2b3c-f145-11e7-8311-b6d854d409d6.png)

**Comment by Binaryify** [comment]
这几天会升级下

**Comment by Binaryify** [comment]
建议先用着 1.2的版本, npm i vue-qr@1.2.0 --save

**Comment by Binaryify** [comment]
已更新
