### ISSUE TITLE
text传入变量报错

### ISSUE THREAD

**Issue by qinhui6** [Binaryify/vue-qr#19]
![image](https://user-images.githubusercontent.com/19324540/35666130-ca230342-0763-11e8-9e85-6f8f4d9132e9.png)
![image](https://user-images.githubusercontent.com/19324540/35666185-f8902e58-0763-11e8-9109-b8e9d15e8ca0.png)
用 :text传入变量url报错了，麻烦帮忙看一下

**Comment by Binaryify** [comment]
你传的 undefined 了
![image](https://user-images.githubusercontent.com/12221718/35666763-2f56a6ea-0766-11e8-8d65-263f69838cf5.png)

**Comment by qinhui6** [comment]
怎么获取callback值呢？生成的二维码的下载地址

**Comment by Binaryify** [comment]
```vue
<vue-qr :text="text" :autoColor='true' :logoSrc="src2" :size="400" :margin="0" :callback="fun"></vue-qr>
```

```js
methods:{
    fun(url){
      console.log(url)
    }
  }
```
callback 拿到的是 base64

**Comment by liuchang0108** [comment]
if (this._bindElement !== undefined) {
                try {
                    var el = document.getElementById(this._bindElement);
                    if (el.nodeName === 'IMG') {
                        el.src = this._elCanvas.toDataURL();
                    } else {
                        var elStyle = el.style;
                        elStyle["background-image"] = 'url(' + this._elCanvas.toDataURL() + ')';
                        elStyle["background-size"] = 'contain';
                        elStyle["background-repeat"] = 'no-repeat';
                    }
                } catch (e) {
                    console.error(e);
                }
            }
这里报错TypeError: Cannot read property 'nodeName' of null  不知道哪里出了问题

**Comment by Binaryify** [comment]
@liuchang0108 晚点修复
