### ISSUE TITLE
微信、Safari浏览器不支持crossOrigin = 'anonymous'。

### ISSUE THREAD

**Issue by CCWork** [Binaryify/vue-qr#23]
Safari浏览器不支持crossOrigin = 'anonymous'
目前IPhone中微信浏览器内核与safari一致。
源码中这一属性导致logo之类的小图不能用base64
建议删除- -。

**Comment by Binaryify** [comment]
删除和添加都会导致不同的问题,还在想怎么处理好
https://github.com/Binaryify/vue-qr/pull/7

**Comment by varzhangshuai** [comment]
so 怎么目前解决？

**Comment by Binaryify** [comment]
@CCWork 再试试
