### ISSUE TITLE
:bgSrc  :logoSrc 两属性直接赋值"http://xxxxx.png"会报跨域问题

### ISSUE THREAD

**Issue by tustman** [Binaryify/vue-qr#24]
Access to Image at 'http://xxx.yyyyyyyy.com/app/package/2ec8bab90c794f208b6c2137a50dd9db.png' from origin 'http://localhost:9527' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9527' is therefore not allowed access.

如果直接使用img标签可以展示出图片
`<img src="http://xxx.yyyyyyyy.com/app/package/2ec8bab90c794f208b6c2137a50dd9db.png">`

**Comment by xiaoshengxianjun** [comment]
对啊，这个问题怎么解决？求方案

**Comment by tustman** [comment]
@xiaoshengxianjun 
建议你用下面这个试试
import Qrcanvas from 'qrcanvas-vue'

<qrcanvas id="myCanvas" :options="options"></qrcanvas>

const image = new Image()
image.src = this.currentLogo
image.onload = () => {
this.options = Object.assign({}, this.options, {
	  data: 'http://www.xxxxx.png',
	  cellSize: 8,
	  size: 300,
	  logo: {
		image
	  }
	})
}

**Comment by 19L** [comment]
@tustman 
你是怎么处理的？

**Comment by Binaryify** [comment]
试试新版本

**Comment by hanniba214** [comment]
最新版本也没能解决这个问题啊？这个问题为了兼容性暂时是不会解决吗？

**Comment by javascripet** [comment]
> 试试新版本

还是不行哟...

**Comment by whenevery** [comment]
为什么 一定需要发起http请求 获取文件呢？ 是需要获取特定的属性吗 可以做直接加载获取文件信息吗?
https域名里使用http的logo 固定会报错 (某些外部资源就是http的

**Comment by Binaryify** [comment]
@whenevery  加载就是要请求,用代理吧

**Comment by Binaryify** [comment]
@hanniba214 @javascripet 用代理,前端只能解决 canvas 图片被污染的问题,但是无法处理跨域问题

**Comment by DongJigong** [comment]
这个问题还没解决么？

**Comment by Binaryify** [comment]
@DongJigong 图片服务器端得支持 CORS，不然没用

**Comment by DongJigong** [comment]
> @DongJigong 图片服务器端得支持 CORS，不然没用,要么就套一层图片代理
> https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_enabled_image

好的.

**Comment by Vitomir2** [comment]
How the <img> is accepting such url without problems, but the vue-qr is not ?
