### ISSUE TITLE
批量生成多个二维码，回调函数返回的内容不是按顺序返回的

### ISSUE THREAD

**Issue by xiaoshengxianjun** [Binaryify/vue-qr#28]
`<div v-for="item in QRAll" :key="item.id">
          <vue-qr :logoSrc="item.qrLogo" :text="item.qrInfo" :size="1000" :margin="0" :callback="getQR"></vue-qr>
        </div>`
采用如上形式生成了多个二维码，在getQR中将图片数据push到一个数组中，经验证，数组中的图片数据顺序是乱的。

**Comment by Binaryify** [comment]
生成二维码过程是异步的,你 push 的话数据肯定不能保证是顺序的,你有 id 的话可以自行整理

**Comment by Astaca** [comment]
如何整理呢，callback 里面带参 就获取不到回调的ur了

**Comment by Binaryify** [comment]
@xiaoshengxianjun 
@Astaca 
我刚更新了,加了个 qid 参数

**Comment by alextzh** [comment]
循环渲染最后一个二维码渲染不出来
