### ISSUE TITLE
logo跨域问题

### ISSUE THREAD

**Issue by yuyedaidao** [Binaryify/vue-qr#36]
![image](https://user-images.githubusercontent.com/6354958/44656346-15271a80-aa2b-11e8-9a04-462dd77fc7de.png)

设置了logoSrc之后出现canvases的跨域问题，有没有好的解决方案

**Comment by yuyedaidao** [comment]
刚才看了一下你的源码，发现你之前处理过，为什么把 `img.crossOrigin = 'anonymous'` 给注释了又，能放开吗

**Comment by Binaryify** [comment]
再试试新版本
