### ISSUE TITLE
赋值图片给logoSrc,手机端二维码就不显示了，但赋值本地图片给logoSrc就可以

### ISSUE THREAD

**Issue by KaivOU** [Binaryify/vue-qr#37]
![image](https://user-images.githubusercontent.com/36435545/44830351-ea6bda80-ac53-11e8-9807-74c1c2baed13.png)
![image](https://user-images.githubusercontent.com/36435545/44830357-f35cac00-ac53-11e8-9ea9-27619cdd02cb.png)
![image](https://user-images.githubusercontent.com/36435545/44830371-feafd780-ac53-11e8-9dda-270dd6ba6116.png)

我都更新到"vue-qr": "^1.3.8"了，logoSrc传入本地图片可以，传图片链接手机上就显示不了二维码，是logo影响着二维码的生成？

**Comment by KaivOU** [comment]
传入图片为：微信接口返回的头像：http://thirdwx.qlogo.cn/mmopen/wprMnqDUJH69pXBhKHUuNyTcavcYickDnnRtYiaymtnaa3ibFibJZP1qUCDIlndicaTAcAU2c8obdjtCh8GYkL4UicEODUthljibD49/132

**Comment by Binaryify** [comment]
再试试最新版本的

**Comment by Binaryify** [comment]
有些图片服务器不允许跨域的就不行了

**Comment by Binaryify** [comment]
你试试这个
https://avatars1.githubusercontent.com/u/12221718?s=88&v=4

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/45249186-4fa78600-b34e-11e8-8ff4-3f8d08576dc2.png)
@Binaryify  你这张照片可以显示，是允许跨域了是吧。
但是打包报错了

**Comment by KaivOU** [comment]
@Binaryify 是的，启动不报错，打包报错了这个1.4.1版本

**Comment by Binaryify** [comment]
试试最新的 v1.5.1, 找不到就用 npm 官方源装

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/45250357-082bf480-b364-11e8-88bd-57c9d2f23920.png)
@Binaryify 安卓报错，最新还是1.4.1，我开了VPN再npm install vue-qr --save-dev，安卓时还是这个图的报错error，然后还是最新的1.4.1

**Comment by Binaryify** [comment]
用了 nrm 吗,切到官方npm源

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/45250386-88eaf080-b364-11e8-8380-f731a91763b5.png)

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/45250457-27c41c80-b366-11e8-94ce-7c20dc28527f.png)
特意安装了nrm切到官方npm源

**Comment by Binaryify** [comment]
代理什么的关掉

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/45250532-8c33ab80-b367-11e8-91d9-d91f3186de0b.png)
嗯，关掉了所有代理和VPN，也用过了自带的终端来安装npm install vue-qr --save 还是没成，我试了用npm源安装1.3.8都不行，不知道会不会网络问题，用淘宝源就可以，但就是没1.5.1，，我上面的图片，还能用其他源码？1.5.1的

**Comment by Binaryify** [comment]
我刚去 npm 淘宝镜像站手动同步了下,你再试试
![image](https://user-images.githubusercontent.com/12221718/45250560-1da31d80-b368-11e8-8234-3fcdba42ad61.png)
![image](https://user-images.githubusercontent.com/12221718/45250561-24319500-b368-11e8-86ff-6fda87a8a463.png)

**Comment by KaivOU** [comment]
@Binaryify 用淘宝镜像可以升级到1.5.1了，打包也没报错了，然后试了上面你发给我的你那个头像是可以显示的，你是在你的图片库做了跨域处理是吧，我这边接口的图片也需要做跨域处理，那就可以了是吗？

**Comment by Binaryify** [comment]
@KaivOU 
对的,因为服务器不允许跨域的话前端也是没办法解决的,得弄个转发服务器成同域的

**Comment by KaivOU** [comment]
@Binaryify http://thirdwx.qlogo.cn/mmopen/wprMnqDUJH69pXBhKHUuNyTcavcYickDnnRtYiaymtnaa3ibFibJZP1qUCDIlndicaTAcAU2c8obdjtCh8GYkL4UicEODUthljibD49/132  
那就尴尬了，这个是微信的头像的logo，本来就支持跨域的，在任何浏览器都可以打开，在我们这插件里面就出现跨域问题

**Comment by Binaryify** [comment]
确定url没问题吗,我这里是没问题的
![image](https://user-images.githubusercontent.com/12221718/45261518-3c241a00-b437-11e8-9a51-f66ae6301f95.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/45261585-0ed86b80-b439-11e8-9a42-4687cb282de5.png)

**Comment by KaivOU** [comment]
我试了还是不行，不知道为什么
<vue-qr :logoSrc="config.logo" :text="config.value" :size="200" :margin="0"></vue-qr>
data() {
    return {
config: {
        value: 'www.baidu.com',//显示的值、跳转的地址
        logo: "http://thirdwx.qlogo.cn/mmopen/wprMnqDUJH69pXBhKHUuNyTcavcYickDnnRtYiaymtnaa3ibFibJZP1qUCDIlndicaTAcAU2c8obdjtCh8GYkL4UicEODUthljibD49/132"//中间logo的地址
      }}}
参数都配在这里了，webpack里面的那个proxyTable也关了，
用你那个https的头像就行，有没有头绪提点下，还是报错。我的代码有问题吗？
![image](https://user-images.githubusercontent.com/36435545/45311104-b9947b00-b55a-11e8-8894-d22090549e1c.png)

**Comment by Binaryify** [comment]
你弄个空项目重新试试
