### ISSUE TITLE
logoSrc传入本地图片转换的base64图片，在安卓手机端整个二维码显示不出来

### ISSUE THREAD

**Issue by willson-wang** [Binaryify/vue-qr#39]
vue-qr版本：1.3.0

本地图片转换成base64
![image](https://user-images.githubusercontent.com/20950813/45401392-fc517280-b682-11e8-815f-8c30b1fb7225.png)

生成二维码
![image](https://user-images.githubusercontent.com/20950813/45401408-0b382500-b683-11e8-9290-bbbff2ba7405.png)

在安卓手机内提示跨域，导致整个二维码显示不出来
![image](https://user-images.githubusercontent.com/20950813/45401506-7a157e00-b683-11e8-822b-cc4be2f7db72.png)

![image](https://user-images.githubusercontent.com/20950813/45401355-d88e2c80-b682-11e8-91c8-9b9e043704ce.png)

去掉logoSrc就能够正常显示

![image](https://user-images.githubusercontent.com/20950813/45401470-53574780-b683-11e8-8d60-9ebbf71c752f.png)

**Comment by Binaryify** [comment]
请更新到1.5版本

**Comment by wenxuancheung** [comment]
现在就是1.5.1版本

**Comment by Binaryify** [comment]
我加个判断吧

**Comment by Binaryify** [comment]
更新到 1.5.2 试试
