### ISSUE TITLE
扫码以后可以跳转到指定url吗？

### ISSUE THREAD

**Issue by NinjaJin** [Binaryify/vue-qr#4]
扫码以后可以跳转到指定url吗？

**Comment by Binaryify** [comment]
文本内容换成 url就行

**Comment by Ceeson** [comment]
我文本内容是url，但是他跳转后前面会加上运行环境的ip，这个怎么去掉？
例如这样：http://127.0.0.1:8080/resources/http://static.sse.com.cn/disclosure/listedinfo/announcement/c/2020-04-28/603398_20200428_9.pdf
