### ISSUE TITLE
在vue子组件里使用vue-qr 一直报解析error

### ISSUE THREAD

**Issue by Crownguan** [Binaryify/vue-qr#49]
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|   <div v-if="bindElement">
|     <img v-bind="{id:uuid}">

**Comment by Crownguan** [comment]
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| 
|


|

**Comment by Binaryify** [comment]
你是 vue-cli 下使用的吗

**Comment by Crownguan** [comment]
不是

**Comment by Crownguan** [comment]
vue的版本 2.4.2  vue-loader 13.0.4

**Comment by Binaryify** [comment]
因上层支持库的原因，暂时不支持非 vue-cli 项目下使用

**Comment by Crownguan** [comment]
ok

**Comment by Binaryify** [comment]
再试试，已经重构了，改写了上游的支持库

**Comment by Crownguan** [comment]
👌

原始邮件
发件人:阿发notifications@github.com
收件人:Binaryify/vue-qrvue-qr@noreply.github.com
抄送:王冠（wangguan）18601619930@163.com; Authorauthor@noreply.github.com
发送时间:2019年3月27日(周三) 16:49
主题:Re: [Binaryify/vue-qr] 在vue子组件里使用vue-qr 一直报解析error (#49)


再试试，已经重构了，改写了上游的支持库
