### ISSUE TITLE
text属性不能用v-bind吗

### ISSUE THREAD

**Issue by NinjaJin** [Binaryify/vue-qr#5]
<vue-qr :text="qrText" height="200" width="200"></vue-qr>
动态修改qrText的时候，如何刷新二维码

**Comment by Binaryify** [comment]
疏忽了这种情况,下个版本会增加这个特性

**Comment by Binaryify** [comment]
@NinjaJin 
已更新

**Comment by BlueBoyC** [comment]
<vue-qr logoSrc="/assets/images/activity/shaisuogu/btn_bg.png" text="Hello world!" height="200" width="200"></vue-qr>

照着demo写的，debugger看了一下，好像是少了找不到_bindElement这个
------------
以下是报错的

TypeError: Cannot read property 'nodeName' of null
    at Drawing.webpackJsonp.471.Drawing.draw (awesome-qr.js:1042)
    at AwesomeQRCode.webpackJsonp.471.AwesomeQRCode.makeCode (awesome-qr.js:1204)
    at AwesomeQRCode.webpackJsonp.471.AwesomeQRCode.create (awesome-qr.js:1196)
    at VueComponent.render (vue-qr.js:83)
    at VueComponent.boundFn [as render] (vue.runtime.esm.js:123)
    at Image._img.onload (vue-qr.js:73)

**Comment by KaivOU** [comment]
![image](https://user-images.githubusercontent.com/36435545/44797736-7fce8680-abe2-11e8-804c-664a166f278c.png)
![image](https://user-images.githubusercontent.com/36435545/44797753-8b21b200-abe2-11e8-8953-77ac609bb21a.png)
![image](https://user-images.githubusercontent.com/36435545/44797766-9379ed00-abe2-11e8-8853-15f9cb7a9c58.png)
我都更新到"vue-qr": "^1.3.8"了，接口赋值给text和logoSrc都不行，二维码还没刷新

**Comment by KaivOU** [comment]
@Binaryify 能否帮忙解决下

**Comment by KaivOU** [comment]
是否机上没显示，最新的二维码，微信开发者工具有显示

**Comment by KaivOU** [comment]
找到一点原因，logoSrc传入本地图片可以，传图片链接手机上就显示不了二维码，是logo影响着二维码的生成？@Binaryify @ Binaryify
