### ISSUE TITLE
vue cli为什么更新不了呢

### ISSUE THREAD

**Issue by aiyuchen** [Binaryify/vue-qr#51]
![image](https://user-images.githubusercontent.com/578141/55073145-ec056000-50c7-11e9-94bf-eadb38f1d8e8.png)
没有更新的按钮

**Comment by Binaryify** [comment]
手动更新吧

**Comment by aiyuchen** [comment]
其他的插件都能直接更新的，是不是版本号有点问题呢

**Comment by Binaryify** [comment]
1.x 到 2.x 跨大版本肯定不能直接更新啊
