### ISSUE TITLE
dotScale的默认值

### ISSUE THREAD

**Issue by pkjy** [Binaryify/vue-qr#52]
v2.0.3版本里面，dotScale的默认值是1，与目前的文档一直。
v2.0.4版本里面，dotScale的默认值改为了0.35。。。但是文档还是显示的1。
希望更新一下文档，并且这个值是跟二维码的样式有关的。

**Comment by Binaryify** [comment]
感谢反馈，在家更新忘记提交了，晚点回到家提交下，dotScale 默认为1在一些情况下会导致背景图失效，上游库的默认值也一直是0.35，之前一直没留意到这个问题

**Comment by Binaryify** [comment]
好了
