### ISSUE TITLE
能不能不加polyfill

### ISSUE THREAD

**Issue by ben-lau** [Binaryify/vue-qr#53]
我的项目内置了polyfill了  编译后发现vue-qr内也有  导致报错 
`Uncaught Error: only one instance of babel-polyfill is allowed`
要求运行环境支持es7就好了啊

**Comment by Binaryify** [comment]
已更新

**Comment by ben-lau** [comment]
你好，你的npm包未编译就上传了

**Comment by Binaryify** [comment]
npm publish 有就行，不需要上传污染仓库

**Comment by Binaryify** [comment]
是我漏了 build 就发布 npm 了吗

**Comment by ben-lau** [comment]
没有哦 
![image](https://user-images.githubusercontent.com/16952163/55374686-f39b8d80-553b-11e9-8faf-38ef3a3346c0.png)
你的package入口是dist/vue-qr  直接没了dist目录  忘了构建吧？

**Comment by Binaryify** [comment]
稍等

**Comment by Binaryify** [comment]
再试试

**Comment by Binaryify** [comment]
没设置 npmignore 会直接把 gitnore 复制一份成 npmignore，忽略了 dist，挺坑的，刚加了

**Comment by ben-lau** [comment]
哈哈  可以了  感谢作者  好效率啊

**Comment by Binaryify** [comment]
👌
