### ISSUE TITLE
安装引用后出现 "export 'default' (imported as 'VueQr') was not found in 'vue-qr'是啥原因

### ISSUE THREAD

**Issue by chysos** [Binaryify/vue-qr#54]
WARNING in ./node_modules/babel-loader/lib??ref--1-oneOf-1!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Merchant/Info.vue?vue&type=script&lang=js&
145:25-30 "export 'default' (imported as 'VueQr') was not found in 'vue-qr'
 @ ./node_modules/babel-loader/lib??ref--1-oneOf-1!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Merchant/Info.vue?vue&type=script&lang=js&
 @ ./src/views/Merchant/Info.vue?vue&type=script&lang=js&
 @ ./src/views/Merchant/Info.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/main

**Comment by skydsai** [comment]
@chysos 我也遇到类似的情况
