### ISSUE TITLE
默认二维码样式有点丑呀

### ISSUE THREAD

**Issue by Crownguan** [Binaryify/vue-qr#55]
2.0.7默认生成的二维码有点丑 如何配置才能正常点
![企业微信截图_ebcf69ae-76cb-49e1-a47b-4ca788b5f317](https://user-images.githubusercontent.com/20539133/56026091-06853d80-5d46-11e9-868f-4e827a96e9ac.png)
![image](https://user-images.githubusercontent.com/20539133/56026206-41877100-5d46-11e9-93bb-b0e939639a5b.png)

**Comment by Binaryify** [comment]
dot 设为1

**Comment by Crownguan** [comment]
> dotScale 设为1

👌
