### ISSUE TITLE
背景问题

### ISSUE THREAD

**Issue by xuewanyun** [Binaryify/vue-qr#56]
怎么设置为默认的黑白色 不要彩色的   像草料 那样

**Comment by Binaryify** [comment]
默认本来就是黑白啊

**Comment by xuewanyun** [comment]
![image](https://user-images.githubusercontent.com/17821837/56503793-18868d80-6549-11e9-9a28-22aa09129706.png)

**Comment by xuewanyun** [comment]
我默认这样的

**Comment by xuewanyun** [comment]
![image](https://user-images.githubusercontent.com/17821837/56504056-eaee1400-6549-11e9-9e3d-4880cf878a4f.png)

我就是这样引用的  然后渲染出来就是这样  是 哪里的问题呢

**Comment by Binaryify** [comment]
dotScale 设置为1

**Comment by xuewanyun** [comment]
好了 谢谢  解答  一个star
