### ISSUE TITLE
字符test超过18位就会出现白块,请问如何处理

### ISSUE THREAD

**Issue by zhouxbalabala** [Binaryify/vue-qr#58]
![下载](https://user-images.githubusercontent.com/28882478/57192468-79f42680-6f63-11e9-9832-842328f276b4.png)

**Comment by Binaryify** [comment]
版本号是多少的

**Comment by zhouxbalabala** [comment]
就是当前版本,不过我已经解决了, 更改backgroundColor 颜色就好了

**Comment by Binaryify** [comment]
你的参数是怎样的，我修复下

**Comment by zhouxbalabala** [comment]
`<vue-qr text="https://exg=QE31AD" :correctLevel="1" colorLight="rgb(0,111,0)" :dotScale="1" :size="400" :margin="0"></vue-qr>`
 关键参数是在dotScale,设大是为了美观, 但是就会出现colorLight覆盖不全的情况

**Comment by Takicheng** [comment]
你好，请问为什么我改了背景颜色会是这样的
![image](https://user-images.githubusercontent.com/42823161/115103132-23325c80-9f82-11eb-84e9-066cd0f6f454.png)
`:colorDark="qr.color"
      :colorLight='qr.backgroundColor'
      :backgroundColor="qr.backgroundColor"`
我设置了这几个属性
