### ISSUE TITLE
请问一下二维码的样式问题

### ISSUE THREAD

**Issue by aiyuchen** [Binaryify/vue-qr#64]
版本是：`"vue-qr": "^2.1.0",`
代码如下：
```
<vue-qr :text="shareUrl" :size="400" />
```

生成的图片是这样的：
![image](https://user-images.githubusercontent.com/578141/61149582-0d257b80-a514-11e9-82f6-3ba231564d07.png)

我在其他网站使用相同的内容生成的二维码是这样的：
![image](https://user-images.githubusercontent.com/578141/61149623-2b8b7700-a514-11e9-9909-fe5424d59c09.png)

请问如何将二维码设置成下面这种样式？

**Comment by Binaryify** [comment]
dotScale 设为1

**Comment by aiyuchen** [comment]
@Binaryify 谢谢
