### ISSUE TITLE
dotScale为1时背景图显示异常

### ISSUE THREAD

**Issue by BWmelon** [Binaryify/vue-qr#65]
你好，请问一下参数dotScale为1时背景图显示异常怎么办，dotScale为默认值时背景图显示异常，但是二维码会显示左侧和上面的定位图形。
![](https://imgs.bwmelon.com/20190824153247.png)
然后看其他issue如果想去除定位图形，需要将dotScale值设为1，设置完成后定位图形没了但是背景图就会显示异常。
![](https://imgs.bwmelon.com/20190824153747.png)

**Comment by Binaryify** [comment]
这个是上游库的 bug,不好修

**Comment by Binaryify** [comment]
已修复
