### ISSUE TITLE
logoMargin参数设置无效

### ISSUE THREAD

**Issue by aboutZZ** [Binaryify/vue-qr#67]
`logoMargin`参数设置后，二维码中间的logo边距仍然为`0`

![MSxGxf.png](https://s2.ax1x.com/2019/11/05/MSxGxf.png)

**Comment by Binaryify** [comment]
你是怎么设置的

**Comment by Binaryify** [comment]
图挂了,看不到

**Comment by aboutZZ** [comment]
> 你是怎么设置的

@Binaryify 
代码如下：
`<vue-qr :logo-src="qrCodeLogo" :text="qrCodeText" :size="512" :dot-scale="1" :correct-level="3" :logo-margin="8" />`


得到的二维码图像如下：
![下载.png](https://i.loli.net/2019/11/06/KUpVv3rmQMTAB9L.png)

**Comment by Binaryify** [comment]
驼峰
logoMargin

**Comment by aboutZZ** [comment]
改成下面的驼峰属性名问题依旧
`<vue-qr :logo-src="qrCodeLogo" :text="qrCodeText" :size="512" :dot-scale="1" :correct-level="3"  :logoMargin="8" />`


PS：不是驼峰的问题，Vue会自动映射驼峰名到横杠的吧。`logo-src`属性已经生效了，说明映射了，否则logo根本加载不出来

**Comment by Binaryify** [comment]
确实有 bug,默认 margin 是透明的,我修复下

**Comment by Binaryify** [comment]
你可以暂时指定 logoBackgroundColor="white"

**Comment by Binaryify** [comment]
已修复~
