### ISSUE TITLE
nuxt引入的vue-qr生成的二维码不是img图片

### ISSUE THREAD

**Issue by wenjinlei** [Binaryify/vue-qr#70]
nuxt框架下引入的vue-qr生成了二维码，但二维码确不是一张图片，vue-qr还是做为标签存在html结构里，二维码成了这个标签的背景，包是通过公司的镜像资源装的，用自己的电脑新起一个nuxt项目引入vue-qr生成的又是图片

**Comment by fc653074701** [comment]
请问这个后来怎么解决的？ @wenjinlei

**Comment by Binaryify** [comment]
暂时不支持服务端渲染，用v-if控制渲染，页面mounted后修改v-if的状态就行

**Comment by fc653074701** [comment]
> 临时不支持服务端渲染，用v-if控制渲染，页面安装后修改v-if的状态就行

可以

**Comment by Binaryify** [comment]
新版本支持ssr了

**Comment by chhumsina** [comment]
> The new version supports ssr


我已经将版本更新为最新版本，但仍然无法正常使用，您能给我介绍如何使用二维码ssr

**Comment by chhumsina** [comment]
> 新版本支持ssr了

我已经将版本更新为最新版本，但仍然无法正常使用，您能给我介绍如何使用二维码ssr

**Comment by Binaryify** [comment]
@chhumsina v2.3.0？

**Comment by chhumsina** [comment]
> @chhumsina v2.3.0？

I use this: "vue-qr": "^2.3.0"

**Comment by chhumsina** [comment]
> @chhumsina v2.3.0？

"vue-qr": "^2.3.0"

**Comment by chhumsina** [comment]
> @chhumsina v2.3.0？

work fine now,
thank you
