### ISSUE TITLE
为什么我的二维码颜色很奇怪

### ISSUE THREAD

**Issue by Takicheng** [Binaryify/vue-qr#86]
![image](https://user-images.githubusercontent.com/42823161/115103072-896aaf80-9f81-11eb-933f-5115c220c932.png)
`:colorDark="#28D905"
      :colorLight='#EB0303'
      :backgroundColor="#EB0303"`
设置了这三个属性，为什么背景不是全红的，里面是盖了点白的

**Comment by Takicheng** [comment]
@Binaryify

**Comment by Binaryify** [comment]
awesome-qr 这个库的代码有些问题
![image](https://user-images.githubusercontent.com/12221718/116192786-e5db8500-a760-11eb-93b4-21b24277a670.png)
这行代码有问题，不知道是出于什么用意，我估计五一这段时间才有时间改

**Comment by Takicheng** [comment]
> awesome-qr 这个库的代码有些问题
> ![image](https://user-images.githubusercontent.com/12221718/116192786-e5db8500-a760-11eb-93b4-21b24277a670.png)
> 这行代码有问题，不知道是出于什么用意，我估计五一这段时间才有时间改

麻烦大佬了

**Comment by Binaryify** [comment]
好了，你更新下看看

**Comment by Takicheng** [comment]
> 好了，你更新下看看

谢谢
