### ISSUE TITLE
生成的二维码不能识别

### ISSUE THREAD

**Issue by EastemChen** [Binaryify/vue-qr#88]
![image](https://user-images.githubusercontent.com/19586337/118713699-d5489700-b854-11eb-8f6b-ca4035fdb05e.png)

![image](https://user-images.githubusercontent.com/19586337/118716150-180b6e80-b857-11eb-87ec-a82151cb04c0.png)

用这个库生成的二维码用qrcode-decoder这个库无法解析.麻烦看一下,谢谢!

**Comment by hearain** [comment]
这是最新版本的一个问题，可以降级到2.2.1版本

**Comment by Binaryify** [comment]
晚点我回滚下吧，上游那个仓库有不少问题，改它的代码还容易出问题

**Comment by EastemChen** [comment]
> 晚点我回滚下吧，上游那个仓库有不少问题，改它的代码还容易出问题

回滚后问题已解决,谢谢

**Comment by EastemChen** [comment]
> 这是最新版本的一个问题，可以降级到2.2.1版本

应该是版本的问题的,谢谢

**Comment by xu-Aurora** [comment]
> 这是最新版本的一个问题，可以降级到2.2.1版本

我回滚到2.2.1还是不行。目前的是android上二维码是有效的，ios上二维码是无效的
