### ISSUE TITLE
transform-runtime 未写入package.json

### ISSUE THREAD

**Issue by dongnaebi** [Binaryify/vue-qr#9]
引用就报错了：Unknown plugin "transform-runtime" specified in "\\node_modules\\vue-qr\\.babelrc" at 0

**Comment by Binaryify** [comment]
确定没有吗
![image](https://user-images.githubusercontent.com/12221718/30997262-33e3be7e-a48c-11e7-862b-e396c7ff3c94.png)

**Comment by dongnaebi** [comment]
那是打包的问题？npm的包import就报错

**Comment by Binaryify** [comment]
能提供具体的步骤和细节吗
