### ISSUE TITLE
vite vue3 引入时

### ISSUE THREAD

**Issue by naimao001** [Binaryify/vue-qr#90]
![image](https://user-images.githubusercontent.com/41824750/119958494-ac06d400-bfd5-11eb-9c33-381898b89a54.png)

**Comment by Binaryify** [comment]
// vue3.0
import vueQr from 'vue-qr/src/packages/vue-qr.vue'

**Comment by naimao001** [comment]
我就是这么导入的

**Comment by naimao001** [comment]
![image](https://user-images.githubusercontent.com/41824750/119960384-7b279e80-bfd7-11eb-93ef-7481fe2322fe.png)

**Comment by naimao001** [comment]
版本确认了 是2.4.0的

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/119962291-77951700-bfd9-11eb-857d-c70d8ad40c35.png)
无法重现

**Comment by naimao001** [comment]
卧槽  我自己折腾一下 可能是打包 或者vite 引包的问题

**Comment by naimao001** [comment]
![image](https://user-images.githubusercontent.com/41824750/120256308-6ccfd000-c2c0-11eb-926c-2232d352c2f2.png)

**Comment by naimao001** [comment]
上图是在正常vite官方文档 脚手架搭建的项目
