### ISSUE TITLE
设置了logo之后， margin参数 只有上左有边距， 下右没有边距

### ISSUE THREAD

**Issue by phpgiter** [Binaryify/vue-qr#91]
![image](https://user-images.githubusercontent.com/26064554/120293862-3ca42380-c2f8-11eb-8966-e0ee03e9059f.png)
像这个图一样， margin设置的10， 但是只有上边 左边有边距，下边 右边没有， 不添加logo，一切正常，红色部分是父元素设置的背景颜色，方便调试

**Comment by JohnsonHwuang** [comment]
同样的问题

**Comment by PineSongCN** [comment]
设置了logoSrc之后出现这个问题

**Comment by PineSongCN** [comment]
@JohnsonHwuang

**Comment by PineSongCN** [comment]
退回2.3.0版本后正常了。

**Comment by denglouhen** [comment]
大佬修下bug吧，搞得今天上线都出错了，边距和中间logo报错问题都遇到了，2.4.0没法用，只能回退2.3.0。太坑了

**Comment by Binaryify** [comment]
版本回滚了，更新下 2.5.0 @denglouhen
